FROM wordpress
RUN chown -R www-data:www-data /var/www
RUN find /var/www/ -type d -exec chmod 0755 {} \;
RUN find /var/www/ -type f -exec chmod 644 {} \;
#WORKDIR /var/www/wp-content
#COPY plugins plugins/